apiVersion: apps/v1
kind: Deployment
metadata:
 name: k3s
 labels:
  app: k3s
spec:
 selector:
  matchLabels:
   app: k3s
 replicas: 1
 template:
  metadata:
   labels:
    app: k3s
  spec:
   containers:
   - name: k3s
     image: rancher/k3s:latest
     args: ["server","--kubelet-arg","port=10350","--kubelet-arg","healthz-port=10348","--kube-proxy-arg","healthz-bind-address=0.0.0.0:10356","--kube-proxy-arg","metrics-bind-address=127.0.0.1:10349","--kube-scheduler-arg","port=10351"]
     env:
     - name: K3S_TOKEN
       value: "f7b5d6eab0aa000d7a8615065a40e40b"
     - name: K3S_KUBECONFIG_OUTPUT
       value: "/output/kubeconfig.yaml"
     - name: K3S_KUBECONFIG_MODE
       value: "666"
     volumeMounts:
     - mountPath: /var/lib/rancher/k3s
       name: k3s-server
     securityContext:
      privileged: true
   hostNetwork: true
   volumes:
   - name: k3s-server
     emptyDir: {}

